// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CasesService.proto

package gr;

/**
 * Protobuf enum {@code gr.CasesEnum}
 */
public enum CasesEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CONFIRMED = 0 [(.gr.name) = "CONFIRMED"];</code>
   */
  CONFIRMED(0),
  /**
   * <code>DEATHS = 1 [(.gr.name) = "DEATHS"];</code>
   */
  DEATHS(1),
  /**
   * <code>RECOVERED = 2 [(.gr.name) = "RECOVERED"];</code>
   */
  RECOVERED(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CONFIRMED = 0 [(.gr.name) = "CONFIRMED"];</code>
   */
  public static final int CONFIRMED_VALUE = 0;
  /**
   * <code>DEATHS = 1 [(.gr.name) = "DEATHS"];</code>
   */
  public static final int DEATHS_VALUE = 1;
  /**
   * <code>RECOVERED = 2 [(.gr.name) = "RECOVERED"];</code>
   */
  public static final int RECOVERED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CasesEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CasesEnum forNumber(int value) {
    switch (value) {
      case 0: return CONFIRMED;
      case 1: return DEATHS;
      case 2: return RECOVERED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CasesEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CasesEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CasesEnum>() {
          public CasesEnum findValueByNumber(int number) {
            return CasesEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return gr.CasesServiceOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final CasesEnum[] VALUES = values();

  public static CasesEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CasesEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:gr.CasesEnum)
}

