// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CasesService.proto

package gr;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gr.Empty)
    com.google.protobuf.MessageOrBuilder {
}
