// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CasesService.proto

package gr;

public interface requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gr.request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gr.CasesEnum casesType = 1;</code>
   * @return The enum numeric value on the wire for casesType.
   */
  int getCasesTypeValue();
  /**
   * <code>.gr.CasesEnum casesType = 1;</code>
   * @return The casesType.
   */
  gr.CasesEnum getCasesType();
}
